<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('daily_question_templates', function (Blueprint $table) {
            $table->id();
            $table->date('question_date')->unique();

            // Question generated by AI
            $table->text('question');
            $table->string('category'); // romantic, fun, deep, future, memories, preferences
            $table->string('locale', 10)->default('id'); // id, en, etc

            // AI metadata
            $table->string('ai_model')->nullable(); // e.g., 'gemini-2.0-flash'
            $table->json('ai_response')->nullable(); // Full AI response for debugging
            $table->boolean('is_fallback')->default(false); // true if using fallback static questions

            $table->timestamps();

            // Indexes
            $table->index('question_date');
            $table->index('category');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('daily_question_templates');
    }
};
